### ISSUE TITLE
Post rate/limit?

### ISSUE THREAD

**Issue by hroafelme** [embolalia/willie#710]
Hello, I have tried searching around and not found any way to add a post rate/limit for messages.

I would like that the bot only post every 10 seconds for everyone, not just a rate on single user.

I tried joining the irc chat but it says I'm banned (#tech Cannot join channel (+b)) is https://chat.dftba.net/ banned?

In bot.py#644 it says if self.config.has_section('limit'): but that don't seem to work either.

**Comment by tyrope** [comment]
Due to frequent spammers in #tech, the channel op has decided to ban webchat and mibbit. Please get an IRC client to connect there.

As for [bot.py#644](https://github.com/embolalia/willie/blob/master/willie/bot.py#L644) This is the first time I hear of a 'limit' section, so I'm not surprised it doesn't work. What I do know is that the current built-in rate limiter should suffice for any anti-flooding the IRCd has setup.

**Comment by embolalia** [comment]
Overall rate limiting is done by arcane magic with outdated comments in [this general area](https://github.com/embolalia/willie/blob/master/willie/irc.py#L419-L449). The wisdom of the ancients says that this was calculated carefully to be as frequent as possible without running into server-side limits. Until someone can prove that mythology false, I don't intend to upset the gods by changing it. You can do so in your own fork, of course.

**Comment by hroafelme** [comment]
Okey, Thank you!

Also, when I get errors the bot posts it to chat. Is it something on my side? Python27 on Windows 8 running willie in a normal CMD.

I get it in both my own and the standard modules like youtube.py

For example 

> 23:43 Willie: HTTPError: HTTP Error 404: Not Found (file "C:\Python27\lib\urllib2.py", line 531, in http_error_default)

Or is there some setting to disable this?
