### ISSUE TITLE
Bot post errors to chat

### ISSUE THREAD

**Issue by hroafelme** [embolalia/willie#717]
When I get errors the bot posts it to chat. Is it something on my side? Python27 on Windows 8 running willie in a normal CMD.

I get it in both my own and the standard modules like youtube.py

For example 

> 23:43 Willie: HTTPError: HTTP Error 404: Not Found (file "C:\Python27\lib\urllib2.py", line 531, in http_error_default)

Or is there some setting to disable this?

**Comment by prestonconnors** [comment]
I am also interested in a way to prevent this output.

**Comment by embolalia** [comment]
Please provide the output to `.version` and the relevant parts from `exceptions.log`.

**Comment by hroafelme** [comment]
I know why the error exist, I just want to disable that the output goes to chat. I would only like it in log or terminal.

>Willie v. 5.0.0-beta at commit: a8e7c6c58963d3d1fbea759c5914fb37f6fb7376

--

> Signature: Exception: CA Certificate bundle /etc/ssl/certs/ca-certificates.crt is not readable (file "C:\Users\Administrator\Documents\GitHub\willie\willie\web.py", line 165, in connect)
from jerlstrom at 2015-01-12 11:53:09.628000. Message was: http://www.youtube.com/watch?v=Bznxx12Ptl0
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\willie\willie\bot.py", line 634, in call
    exit_code = func(willie, trigger)
  File "C:\Users\Administrator\Documents\GitHub\willie\willie\modules\youtube.py", line 167, in ytinfo
    video_info = ytget(bot, trigger, uri)
  File "C:\Users\Administrator\Documents\GitHub\willie\willie\modules\youtube.py", line 39, in ytget
    bytes = web.get(uri)
  File "C:\Users\Administrator\Documents\GitHub\willie\willie\web.py", line 67, in get
    u = get_urllib_object(uri, timeout, headers, verify_ssl)
  File "C:\Users\Administrator\Documents\GitHub\willie\willie\web.py", line 216, in get_urllib_object
    u = opener.open(req, None, timeout)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\Documents\GitHub\willie\willie\web.py", line 175, in https_open
    return self.do_open(VerifiedHTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1181, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "C:\Python27\lib\httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 829, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 791, in send
    self.connect()
  File "C:\Users\Administrator\Documents\GitHub\willie\willie\web.py", line 165, in connect
    raise Exception('CA Certificate bundle %s is not readable' % ca_certs)
Exception: CA Certificate bundle /etc/ssl/certs/ca-certificates.crt is not readable

---

> Signature: HTTPError: HTTP Error 404: Not Found (file "C:\Python27\lib\urllib2.py", line 531, in http_error_default)
from wigoor at 2015-01-12 12:26:26.789000. Message was: !online hitbox.tv/wigoor
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\willie\willie\bot.py", line 634, in call
    exit_code = func(willie, trigger)
  File "C:\Users\Administrator\.willie\modules\online.py", line 13, in online
    response = urllib2.urlopen(url)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

**Comment by embolalia** [comment]
There are two different things causing this error. From YouTube, it's an SSL issue that may have been clarified since you posted this issue. From your own module, it's because your own module isn't handling the error, which is something you need to do in your own module.

**Comment by hroafelme** [comment]
But why is the bot posting it to chat? Shouldn't the error be sent to terminal or a log file as standard and not message the error to 1000 of users? I have never seen coding that present error messages as standard to the end user.

It's not only my own modules like I said. tools.py have given error etc when timezone is incorrect. It's so annoying i stopped using the bot. Also the fact that the bot doesn't have a post limit. 3 sec cooldown is not enough for a chat with +1000 users daily.

The bot is very easily abused. As you stated your channel gets spammed so much you banned webchat might be an indication? 

The lack of proper documentation is also a sad fact. If you ask a dev something that in "Core configuration settings" and he said he didn't know that existed it just feels very wrong.

Thanks for answering tho and your time developing the bot. I don't mean to sound to harsh.

**Comment by embolalia** [comment]
To be clear, the reason webchat was disabled in #tech on irc.dftba.net is because the owner of that channel felt it was being used by people who were being disruptive in the channel in general, in part due to the increased visibility of the channel when it was the primary place for Willie support. Other channels where Willie is present, including the current support channel on Freenode, do not ban webchat. Willie, as a bot, has absolutely nothing to do with the banning of webchat in #tech.

Additionally, Willie does have an overall rate limit. It is intended to keep the bot from being silenced by the server, and nothing more. Willie was designed for use cases where hundreds of users is a lot, let alone thousands. Issues like #718 will help with that scalability, and the scope of the project may eventually expand to explicitly target high-traffic environments like the one you describe, but it's not currently as high-priority as solving issues that are independent of traffic.

Speaking of which, the lack of documentation, and especially configuration documentation, is a known problem, and #708 was created primarily to address that problem. Currently, I'm the only person doing any documentation work at all on this project, and I only have so much time and energy with which to do so. If you see something in the documentation which is lacking, please do feel free to submit a pull request or edit the wiki, as appropriate. I do consider documentation problems to be bugs, so if you don't know the appropriate thing to edit, feel free to file an issue about it.

Now, to your central point: An exception being sent to the channel is indicative of a bug. The vast, *vast* majority of the time, it is a bug in a module. We do not hide these messages, because it would prevent bugs from being noticed, and therefore prevent them from being fixed. It is a long-standing and well-known issue that Willie has poor test coverage, and given the extremely limited development resources we have and the general unwillingness of contributors to write tests for us, I don't imagine this will change any time soon. Moreover, Willie has always catered to people who are not necessarily experienced in programming, and having something explicit to say that there is an error is extremely helpful to a beginning programmer. To be absolutely clear: if an exception is being sent to the channel, and it is not coming from your own or a third party module, *file an issue*, or better yet a PR. The goal is to fix problems, and that's the best way to do that.

**Comment by MyWay** [comment]
At least it should be possible to set a fixed channel to send exceptions, if you have the bot inside many channels you will loss these messages. And it's a security issue, too.

**Comment by tyrope** [comment]
RE: "You will lose these messages" -> ~/.willie/logs/exceptions.log
RE: "Security issue" -> File a bug, we fix it. Problem solved.

**Comment by MyWay** [comment]
You can't fix it by filling a bug. If the bot is sending in the channel messages that it should not send, it's too late. By having a fixed channel to post them, or a way to disable exceptions being posted, you can solve this security issue.

**Comment by tyrope** [comment]
From IRC:
```
[1631.25] <Eyore> Tyrope: do you understand what security issue he is talking about?
[1708.52] <@embolalia> I have no idea what the alleged security issue is
[1709.51] <@embolalia> like, okay, someone can see that a specific input causes an error
[1710.16] <@embolalia> and yeah, that's not great. they could potentially DOS the bot or something, or fill up your disk with logs
[1710.27] <@embolalia> but it's an IRC bot. And it's not robust against those attacks in any other way.
[1829.39] <@Tyrope> if there's a security issue in Willie, it's not because of it giving out error codes.
[1830.24] <@Tyrope> The only thing it gives away is the location you have the module stored in... If people can use that, your security problem lies elsewhere.
```

**Comment by MyWay** [comment]
It's not true that you give somebody only the path (which anyway shouldn't appear inside a public chat message, because it's not needed by the user (security principles?)). You can't know what you give to the user in advance. You could possibly give somebody other informations that could lead to serious problems (and not only DOS).

**Comment by embolalia** [comment]
Like I said in the quote, there are countless ways to DOS Willie. There are, undoubtedly, countless security holes in Willie. It is an IRC bot. A plaything. Sure, it would be great if it were secure, but right now the other goals of the project are more important.

So, to make this 100% clear: WONTFIX. That is the final word from the BDFL.

**Comment by elad661** [comment]
To calrify: when we find actual security issues in willie, we fix them - while it's a plaything we still do take security seriously.

However, the issue discussed here is **not a security issue** at all. The location in which you installed the bot is not sensitive information.

If you're uncomfortable with this, either install willie in a different path, or don't use it at all.
