### ISSUE TITLE
TypeError: unbound method lower() must be called with Identifier instance as first argument (got unicode instance instead)

### ISSUE THREAD

**Issue by RustyBower** [embolalia/willie#751]
python willie.py --version
Willie 5.1.1-git (running on python 2.7.3)
http://willie.dftba.net/

Traceback (most recent call last):
  File "/opt/willie/willie/bot.py", line 638, in call
    exit_code = func(willie, trigger)
  File "/opt/willie/willie/modules/chanlogs.py", line 133, in log_message
    fpath = get_fpath(bot, message)
  File "/opt/willie/willie/modules/chanlogs.py", line 76, in get_fpath
    channel = willie.tools.Identifier.lower(channel)
TypeError: unbound method lower() must be called with Identifier instance as first argument (got unicode instance instead)

**Comment by harrowed** [comment]
replace it with channel = channel.lower()

**Comment by RustyBower** [comment]
basedir = os.path.expanduser(bot.config.chanlogs.dir)
    channel = channel or trigger.sender
    channel = channel.lstrip("#")
    channel = BAD_CHARS.sub('__', channel)
    channel = channel.lower()

    dt = get_datetime(bot)


This is what I have and I am still getting the following error :(

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/willie-5.1.1_git-py2.7.egg/willie/bot.py", line 638, in call
    exit_code = func(willie, trigger)
  File "/usr/local/lib/python2.7/dist-packages/willie-5.1.1_git-py2.7.egg/willie/modules/chanlogs.py", line 145, in log_join
    fpath = get_fpath(bot, trigger, channel=trigger.sender)
  File "/usr/local/lib/python2.7/dist-packages/willie-5.1.1_git-py2.7.egg/willie/modules/chanlogs.py", line 76, in get_fpath
    channel = willie.tools.Identifier.lower(channel)
TypeError: unbound method lower() must be called with Identifier instance as first argument (got unicode instance instead)

**Comment by harrowed** [comment]
Because you didn't reinstall/edit the installed willie package.
sudo nano +76 /usr/local/lib/python2.7/dist-packages/willie-5.1.1_git-py2.7.egg/willie/modules/chanlogs.py

**Comment by RustyBower** [comment]
Yeah I was just about to edit my comment. It's been a long day.

That workaround seems to be working for me.

**Comment by antdude** [comment]
I assume this is the same for v5.0.0, but I don't know where to edit this since I am a Python newbie. Here are my errors:

$ screen willie
    channel = willie.tools.Identifier.lower(channel)
TypeError: unbound method lower() must be called with Identifier instance as first argument (got unicode instance instead)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/willie/bot.py", line 638, in call
    exit_code = func(willie, trigger)
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 133, in log_message
    fpath = get_fpath(bot, message)
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 76, in get_fpath
    channel = willie.tools.Identifier.lower(channel)
TypeError: unbound method lower() must be called with Identifier instance as first argument (got unicode instance instead)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/willie/bot.py", line 638, in call
    exit_code = func(willie, trigger)
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 133, in log_message
    fpath = get_fpath(bot, message)
  File "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 76, in get_fpath
    channel = willie.tools.Identifier.lower(channel)
TypeError: unbound method lower() must be called with Identifier instance as first argument (got unicode instance instead)


06:34PM ��� Willie [~willie@...] has joined #bots
06:34PM <Willie:#bots> TypeError: unbound method lower() must be called with Identifier
          instance as first argument (got unicode instance instead) (file
          "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 76,
          in get_fpath)
06:34PM <Flexo:#bots> have you thought I was surprised that it was called with Identifier
          instance as first argument (got unicode instance instead) (file
          "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 76,
          in get_fpath)
06:34PM <Willie:#bots> TypeError: unbound method lower() must be called with Identifier
          instance as first argument (got unicode instance instead) (file
          "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 76,
          in get_fpath)
...
��� BitchX: You are now talking to channel #bots
[06:34pm] <Ant> test
06:34PM <Willie> TypeError: unbound method lower() must be called with
          Identifier instance as first argument (got unicode instance instead)
          (file
          "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py",
          line 76, in get_fpath)

**Comment by firerogue** [comment]
The error is saying that you're passing an object of type unicode to a
function that expects an object of type Instance. Your first argument is
channel, which means I guess its unicode. you'll probably have to run
something like `willie.tools.Identifier(channel).lower()` which would first
make an Identifier instance for channel, and then call lower on it
