### ISSUE TITLE
Oper on connect

### ISSUE THREAD

**Issue by Mochaka** [embolalia/willie#752]
How can i get the bot to oper up on connect?

**Comment by harrowed** [comment]
Same way you normally would, it's network dependent.  Little more info would be better..
Which network, are they using Q/Nickserv/Chanserv etc?

**Comment by Mochaka** [comment]
I'm not sure how I would go about running code when the bot connects. Is there a function I can run in a module that will run once the bot connects?
On Tue, Feb 24, 2015 at 8:29 am, harrowed <notifications@github.com> wrote:Same way you normally would, it's network dependent.  Little more info would be better..
Which network, are they using Q/Nickserv/Chanserv etc?

**Comment by harrowed** [comment]
You still fail to reply with what network, if it's nickserv ; https://github.com/embolalia/willie/wiki/Core-configuration-settings  read the comment about nickserv_password

**Comment by Mochaka** [comment]
It's my own IRC Network, and i know about the configuration. 

What I'm asking is, how do i get the bot to /oper <user> <pass> when the bot connects to the irc. I don't see a way to run code once the bot connects.

**Comment by embolalia** [comment]
@harrowed, I think @Mochaka is looking for the network-level oper, not channel operator. The former is part of the RFC, and has nothing to do with network services.

Anyway, you'll need to trigger on the `001` and/or `251` event (debounce it if you do both, though for oper it probably doesn't matter). Use `bot.write` to send whatever the /oper command is actually sending to the server (you may have to read the spec, or look for a raw log in your client). And then don't do any of that, because it's almost certainly a bad security decision.
