### ISSUE TITLE
Allow passwords in the form of an md5 hash

### ISSUE THREAD

**Issue by bigmittens** [embolalia/willie#774]
Please let auth_password work with md5 sums.

**Comment by dgw** [comment]
The value of `auth_password` is sent straight to the server, so there's nothing willie could do about this. The network you're connecting willie to must accept MD5 hashes instead of / in addition to plaintext passwords.

That said, even if the network were to accept an MD5 hash, you'd still be storing that hash in the config file, and someone could still copy it and use it to log in on IRC with the bot's nick. (Presumably that's why you want to use a hash instead?) IRC passwords are sent in plaintext by design, and must therefore be stored in such a way that the bot can read them (unencrypted/unhashed on disk). Connect via SSL if the network supports it (`use_ssl` set to `true` with the proper `port`) and set permissions on your willie config such that only you can read it (e.g. `chmod 700 /path/to/willie.cfg`).

**Comment by embolalia** [comment]
@dgw beat me to it. All good points.

Additionally, if this is actually different from what Willie currently does, I'm not aware of it being a common feature. In order to reduce maintenance burden, we avoid adding one-off things for individual small networks. We also need to know where we can test the feature. Can you cite some examples of networks that have this feature (or, better yet, an RFC defining it)?

**Comment by bigmittens** [comment]
This may have been the stupidest issue I've opened (I've opened some pretty stupid ones).

I remembered doing this with the program 'mpdscribble'. Without thinking I assumed that mpdscribble decrypted the hash and then sent it to last.fm (and somehow no one else would be able to?). It's now occurring to me that that's probably not the case. Closing the issue, sorry.

**Comment by dgw** [comment]
Don't feel too bad about it. Encryption in general isn't a particularly intuitive field, and the whole idea of one-way encryption takes some thought. :) I just have the benefit of having worked with it long enough that I see through a lot of the more common fallacies.
