### ISSUE TITLE
willie.module.interval(*args) issues

### ISSUE THREAD

**Issue by dman777** [embolalia/willie#790]
when using:
```python
@module.interval(15)
def work(bot):
    text = formatting.color('Get to work, testers! ', formatting.colors.RED)
    bold_text = formatting.bold(text)
    bot.msg("#grandmasboy", bold_text)
```
``` 
      jayP: Get to work, testers! 
      jayP: Get to work, testers! 
      jayP: Get to work, testers! 
      jayP: Get to work, testers! 
      jayP: Get to work, testers! 
      jayP: ...
      jayP: ...
      jayP: ...
```

I believe there are 2 separate issues:
* There is a threshold being applied where after 5 times the bot will display `...`
* There is some kind of breakage because after the first 15 second interval is completed, the 15 second interval no longer applies. The `bot.msg` will still run a message at certain intervals, but these intervals are much longer than 15 seconds.

**Comment by dgw** [comment]
The bot outputting `...` is the internal flood protection, and is intentional so the bot can't say the same thing too many times in a row. From the docs:
> If the same text was the message in 5 or more of the last 8 calls to msg, '...' will be sent instead. If this condition is met, and '...' is more than 3 of the last 8 calls, no message will be sent. This is intended to prevent Willie from being caught in an infinite loop with another bot, or being used to spam.

**Comment by tyrope** [comment]
The second part of your issue also sounds like the built-in flood protection. But the time-based protection is powered by Liquid Magic(tm) and we dare not think too hard about it.

**Comment by dman777** [comment]
Digging through old PR comments, I thought all hard limits were removed from the code base and left to the discretion of the developer?

I think flood protection and time-based protection break `interval()`...the end result is behavior different from the method intended behavior. 

Is there any way the developer can have config options/apis for flood protection and time-based protection? I don't like editing the code base it possible.

**Comment by embolalia** [comment]
Saying the same thing every 15 seconds is unfathomably spammy. By design, Willie avoids being unfathomably spammy. It might work to set `willie.tools.jobs.JobScheduler.min_reaction_time` to something smaller than the current 30 to get around the interval limit, and it might work to add a random number of spaces to the end to avoid the repetition protection. You might then hit the sending limit, which slows down sends to avoid getting kicked by a network for spamming, and there's probably some hack to get around that, too.

The reason this is so difficult is that what you are writing is a spambot, and Willie does a whole bunch of things to avoid becoming a spambot.
